stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Testing ci triggering..."
    - sleep 5
    - echo "It worked!"
